const Map words = {
  "app_title": "Kinoko",
  "confirm": "Bestätigen",
  "install_confirm": "Projekt klonen von {url}",
  "yes": "Ja",
  "no": "Nein",
  "add": "Hinzufügen",
  "clone_project": "Klon...",
  "not_installed": "Nicht geklont",
  "select_main_project": "Zum Hauptprojekt auswählen",
  "new_project": "Neues Git-Projekt",
  "new_project_hint": "Git://...",
  "add_project_failed": "Kann nicht hinzugefügt werden, Vielleicht ist es bereits hinzugefügt？",
  "manage_projects": "Projekte verwalten",
  "manga_home": "Manga nach Hause",
  "favorites": "Favoritinnen",
  "history": "Geschichte",
  "chapters": "Kapitel",
  "reverse_order": "Umgekehrte Reihenfolge",
  "order": "Positive Ordnung",
  "no_project_found": "Das Projekt wurde nicht gefunden",
  "can_not_determine_the_context_type": "Kann den Kontexttyp nicht bestimmen",
  "download_list": "Liste herunterladen",
  "delete_item": "Löschen {0}({1})",
  "undo": "Rückgängig machen",
  "search": "Suche",
  "horizontal_flip": "Horizontaler Flip",
  "horizontal_reverse": "Horizontale Umkehrung",
  "vertical_flip": "Vertikaler Flip",
  "portrait": "Porträt",
  "landscape": "Landschaft",
  "download": "Herunterladen",
  "no_prev_chapter": "Kein vorheriges Kapitel",
  "no_next_chapter": "Kein nächstes Kapitel",
  "n_page": "p{0}",
  "delete_item_2": "Item löschen {0}",
  "select_main_project_first": "Wählen Sie zuerst ein Hauptprojekt aus",
  "bootstart": "Bootstart",
  "cancel": "Stornieren",
  "retry": "Wiederholen",
  "settings": "die Einstellungen",
  "framework": "Rahmen",
  "disclaimer": "Haftungsausschluss",
  "disclaimer_content": """
Diese Software ist eine Software, die ein vom Entwickler bereitgestelltes Plug-In-Projekt lädt, um Netzwerkressourcen zu laden und Comics einfach zu durchsuchen. Der in der Software angezeigte Bildressourcentext wird vom Plug-In-Projekt und der Ressourcen-Website bereitgestellt.
Die Software selbst bietet keine Comic-Dienste an. Bitte befolgen Sie die einschlägigen Gesetze und Vorschriften, wenn Sie Comic-Ressourcen verwenden.

Das Copyright der von dieser Software bereitgestellten herunterladbaren Comic-Ressourcen liegt beim ursprünglichen Autor. Es dient nur zu Lern- und Kommunikationszwecken. Bitte kopieren und laden Sie die Dateien gemäß den einschlägigen nationalen Gesetzen und Vorschriften herunter und verwenden Sie sie nicht ohne Genehmigung des Copyright-Inhabers für andere Zwecke. Bei Streitigkeiten aufgrund illegaler Nutzung trägt der Nutzer alle Folgen.
  """,
  "ok": "OK",
  "language": "Sprache",
  "general": "Allgemeines",
  "credits": "Credits",
  "credits_content": """
Liah(Symbol) https://liah0227.itch.io/
""",
  "can_not_open": "Kann nicht öffnen {0}",
  "no_main_project": "Keiner",
  "remove_project": "Projekt entfernen",
  "would_remove_project": "Möchten Sie das Projekt entfernen({0})?",
  "no_card_found": "Keine SDCard gefunden",
  "no_permission": "Keine Erlaubnis",
  "output_to": "Exportieren nach: {0}",
  "directory_name": "Verzeichnisname",
  "name_empty": "Verzeichnis darf nicht leer sein",
  "clear_history": "Möchten Sie die Geschichte löschen?",
  "download_size": "Download-Größe",
  "cached_size": "Zwischengespeicherte Größe",
  "clear_cache": "Möchten Sie den Cache leeren?",
  "clear": "Cache leeren",
  "libraries_hit": "Klonen Sie und wählen Sie ein Projekt zum Hauptprojekt aus, und genießen Sie dann Manga!",
  "instructions": "Anleitung",
  "download_instructions": "",
  "lang": "de",
  "source": "Quelle",
  "source_description": "Die Quellseite Bitte kopieren Sie die Dateien und laden Sie sie gemäß den einschlägigen nationalen Gesetzen und Vorschriften herunter.",
};