const Map words = {
  "app_title": "Kinoko",
  "confirm": "Confirm",
  "install_confirm": "Clone project from {url}",
  "yes": "Yes",
  "no": "No",
  "add": "Add",
  "clone_project": "Clone...",
  "not_installed": "Not Cloned",
  "select_main_project": "Make as main project",
  "new_project": "New Git project",
  "new_project_hint": "Git://...",
  "add_project_failed": "Can not add，Maybe it be added already？",
  "manage_projects": "Manage Projects",
  "manga_home": "Manga Home",
  "favorites": "Favorites",
  "history": "History",
  "chapters": "Chapters",
  "reverse_order": "Reverse Order",
  "order": "Positive Order",
  "no_project_found": "The project is not found",
  "can_not_determine_the_context_type": "Can not determine the context type",
  "download_list": "Download List",
  "delete_item": "Delete {0}({1})",
  "undo": "Undo",
  "search": "Search",
  "horizontal_flip": "Horizontal Flip",
  "horizontal_reverse": "Horizontal Reverse",
  "vertical_flip": "Vertical Flip",
  "portrait": "Portrait",
  "landscape": "Landscape",
  "download": "Download",
  "no_prev_chapter": "No prev Chapter",
  "no_next_chapter": "No next Chapter",
  "n_page": "p{0}",
  "delete_item_2": "Delete item {0}",
  "select_main_project_first": "Select a main project first",
  "bootstart": "Bootstart",
  "cancel": "Cancel",
  "retry": "Retry",
  "settings": "Settings",
  "framework": "Framework",
  "disclaimer": "Disclaimer",
  "disclaimer_content": """
This software is a software that loads a plug-in project provided by the developer to load network resources and browse comics easily. The image resource text appearing in the software is provided by the plug-in project and the resource website.
The software itself does not provide comic services, please follow relevant laws and regulations when using comic resources.

The copyright of the downloadable comic resources provided by this software belongs to the original author. It is for learning and communication purposes only. Please copy and download the files in accordance with relevant national laws and regulations, and do not use them for other purposes without the authorization of the copyright owner; if disputes arise due to illegal use, all consequences shall be borne by the user.
  """,
  "ok": "OK",
  "language": "Language",
  "general": "General",
"credits": "Credits",
"credits_content": """
Liah(Icon) https://liah0227.itch.io/
""",
  "can_not_open": "Can`t open {0}",
  "no_main_project": "None",
  "remove_project": "Remove Project",
  "would_remove_project": "Would you like to remove project({0})?",
  "no_card_found": "No SDCard found",
  "no_permission": "No permission",
  "output_to": "Export to: {0}",
  "directory_name": "Directory name",
  "name_empty": "Directory can not be empty",
  "clear_history": "Would you like to clear the history?",
  "download_size": "Download Size",
  "cached_size": "Cached Size",
  "clear_cache": "Would you like to clear cache?",
  "clear": "Clear Cache",
  "libraries_hit": "Clone and select a project to main project, then enjoy manga!",
  "instructions": "Instructions",
  "download_instructions": "",
  "lang": "en",
  "source": "Source",
  "source_description": "The source page, Please copy and download the files in accordance with relevant national laws and regulations.",
  "v2_title": "Kinoko v2",
  "v2_content": "Kinoko updated! If \"Yes\" be clicked all the old plugins and downloaded manga would be removed.",
  "added_download": "Added {0} items to download queue.",
};