const Map words = {
  "app_title": "Kinoko",
  "confirm": "Confirmar",
  "install_confirm": "Clonar proyecto de {url}",
  "yes": "sí",
  "no": "No",
  "add": "Agregar",
  "clone_project": "Clonar...",
  "not_installed": "No clonada",
  "select_main_project": "Hacer proyecto principal",
  "new_project": "Nuevo proyecto de Git",
  "new_project_hint": "Git://...",
  "add_project_failed": "No se puede agregar, tal vez ya se haya agregado？",
  "manage_projects": "Gestionar proyectos",
  "manga_home": "Manga Hogar",
  "favorites": "Favoritas",
  "history": "Historia",
  "chapters": "Capítulos",
  "reverse_order": "Orden inverso",
  "order": "Orden positiva",
  "no_project_found": "El proyecto no se encuentra",
  "can_not_determine_the_context_type": "No se puede determinar el tipo de contexto",
  "download_list": "Lista de descargas",
  "delete_item": "Eliminar {0}({1})",
  "undo": "Deshacer",
  "search": "Búsqueda",
  "horizontal_flip": "Volteo horizontal",
  "horizontal_reverse": "Inversión horizontal",
  "vertical_flip": "Volteo vertical",
  "portrait": "Retrato",
  "landscape": "Paisaje",
  "download": "Descargar",
  "no_prev_chapter": "Sin capítulo anterior",
  "no_next_chapter": "No hay próximo capítulo",
  "n_page": "p{0}",
  "delete_item_2": "Eliminar elemento {0}",
  "select_main_project_first": "Primero seleccione un proyecto principal",
  "bootstart": "Inicio de arranque",
  "cancel": "Cancelar",
  "retry": "Rever",
  "settings": "Ajustes",
  "framework": "Estructura",
  "disclaimer": "Descargo de responsabilidad",
  "disclaimer_content": """
Este software es un software que carga un proyecto de complemento proporcionado por el desarrollador para cargar recursos de red y buscar cómics fácilmente. El texto del recurso de imagen que aparece en el software lo proporciona el proyecto de complemento y el sitio web del recurso.
El software en sí no proporciona servicios de cómics, siga las leyes y regulaciones pertinentes cuando utilice recursos de cómics.

Los derechos de autor de los recursos de cómics descargables proporcionados por este software pertenecen al autor original. Es solo para fines de aprendizaje y comunicación. Copie y descargue los archivos de acuerdo con las leyes y normativas nacionales pertinentes y no los utilice para otros fines sin la autorización del propietario de los derechos de autor; Si surgen disputas debido a un uso ilegal, todas las consecuencias correrán a cargo del usuario.
  """,
  "ok": "OK",
  "language": "Idioma",
  "general": "General",
  "credits": "Créditos",
  "credits_content": """
Liah(Icono) https://liah0227.itch.io/
""",
  "can_not_open": "No se puede abrir {0}",
  "no_main_project": "Ninguna",
  "remove_project": "Quitar proyecto",
  "would_remove_project": "¿Quieres eliminar el proyecto({0})?",
  "no_card_found": "No se encontró tarjeta SD",
  "no_permission": "Sin autorización",
  "output_to": "Exportar a: {0}",
  "directory_name": "Nombre del directorio",
  "name_empty": "El directorio no puede estar vacío",
  "clear_history": "¿Te gustaría borrar la historia?",
  "download_size": "Tamaño de descarga",
  "cached_size": "Tamaño en caché",
  "clear_cache": "¿Le gustaría borrar el caché?",
  "clear": "Limpiar cache",
  "libraries_hit": "Clona y selecciona un proyecto para el proyecto principal, ¡luego disfruta del manga!",
  "instructions": "Instrucciones",
  "download_instructions": "",
  "lang": "es",
  "source": "Fuente",
  "source_description": "La página de origen, copie y descargue los archivos de acuerdo con las leyes y normativas nacionales pertinentes.",
};