const Map words = {
  "app_title": "Kinoko",
  "confirm": "Confermare",
  "install_confirm": "Clona progetto da {url}",
  "yes": "sì",
  "no": "No",
  "add": "Inserisci",
  "clone_project": "Clone...",
  "not_installed": "Non clonato",
  "select_main_project": "Crea come progetto principale",
  "new_project": "Nuovo progetto Git",
  "new_project_hint": "Git://...",
  "add_project_failed": "Impossibile aggiungere, Forse è già stato aggiunto？",
  "manage_projects": "Gestisci progetti",
  "manga_home": "Manga Casa",
  "favorites": "Preferite",
  "history": "Storia",
  "chapters": "Capitoli",
  "reverse_order": "Ordine inverso",
  "order": "Ordine positivo",
  "no_project_found": "Il progetto non è stato trovato",
  "can_not_determine_the_context_type": "Impossibile determinare il tipo di contesto",
  "download_list": "Elenco download",
  "delete_item": "Elimina {0}({1})",
  "undo": "Disfare",
  "search": "Ricerca",
  "horizontal_flip": "Capovolgimento orizzontale",
  "horizontal_reverse": "Inversione orizzontale",
  "vertical_flip": "Capovolgimento verticale",
  "portrait": "Ritratto",
  "landscape": "Paesaggio",
  "download": "Scarica",
  "no_prev_chapter": "Nessun capitolo precedente",
  "no_next_chapter": "Nessun capitolo successivo",
  "n_page": "p{0}",
  "delete_item_2": "Cancella oggetto {0}",
  "select_main_project_first": "Seleziona prima un progetto principale",
  "bootstart": "Bootstart",
  "cancel": "Annulla",
  "retry": "Riprova",
  "settings": "Impostazioni",
  "framework": "Struttura",
  "disclaimer": "Disclaimer",
  "disclaimer_content": """
Questo software è un software che carica un progetto plug-in fornito dallo sviluppatore per caricare le risorse di rete e sfogliare facilmente i fumetti. Il testo della risorsa immagine che appare nel software è fornito dal progetto plug-in e dal sito web della risorsa.
Il software in sé non fornisce servizi di fumetti, si prega di seguire le leggi e i regolamenti pertinenti quando si utilizzano le risorse di fumetti.

Il copyright delle risorse di fumetti scaricabili fornite da questo software appartiene all'autore originale. È solo per scopi di apprendimento e comunicazione. Copiare e scaricare i file in conformità con le leggi e i regolamenti nazionali pertinenti e non utilizzarli per altri scopi senza l'autorizzazione del proprietario del copyright; in caso di controversie dovute ad un uso illegale, tutte le conseguenze saranno a carico dell'utente.
 """,
  "ok": "OK",
  "language": "Linguaggio",
  "general": "Generale",
  "credits": "Crediti",
  "credits_content": """
Liah(Icona) https://liah0227.itch.io/
""",
  "can_not_open": "Impossibile aprire {0}",
  "no_main_project": "Nessuna",
  "remove_project": "Rimuovi progetto",
  "would_remove_project": "Vuoi rimuovere il progetto({0})?",
  "no_card_found": "Nessuna scheda SD trovata",
  "no_permission": "Nessun permesso",
  "output_to": "Esporta a: {0}",
  "directory_name": "Nome della directory",
  "name_empty": "La directory non può essere vuota",
  "clear_history": "Vuoi cancellare la cronologia?",
  "download_size": "Dimensioni download",
  "cached_size": "Dimensione cache",
  "clear_cache": "Vuoi svuotare la cache?",
  "clear": "Cancella cache",
  "libraries_hit": "Clona e seleziona un progetto nel progetto principale, quindi goditi i manga!",
  "instructions": "Istruzioni",
  "download_instructions": "",
  "lang": "it",
  "source": "Fonte",
  "source_description": "La pagina di origine, copiare e scaricare i file in conformità con le leggi e i regolamenti nazionali pertinenti.",
};