const Map words = {
  "app_title": "木の子",
  "confirm": "請確認",
  "install_confirm": "從 {url} 克隆項目",
  "yes": "是",
  "no": "否",
  "add": "添加",
  "clone_project": "克隆中...",
  "not_installed": "未克隆",
  "select_main_project": "設為主項目",
  "new_project": "添加Git項目",
  "new_project_hint": "Git://...",
  "add_project_failed": "未能添加，是否已添加？",
  "manage_projects": "轄書齋",
  "manga_home": "漫畫之家",
  "favorites": "收藏夾",
  "chapters": "章節列表",
  "reverse_order": "逆序",
  "order": "正序",
  "no_project_found": "沒有找到這個項目",
  "can_not_determine_the_context_type": "不能識別這個數據類型",
  "download_list": "下載列表",
  "delete_item": "刪除 {0}({1})",
  "undo": "取消",
  "search": "尋幽覓勝",
  "horizo​​ntal_flip": "水平翻頁",
  "vertical_flip": "垂直翻頁",
  "portrait": "竪屏",
  "landscape": "橫屏",
  "download": "下載",
  "no_prev_chapter": "無！前一章",
  "no_next_chapter": "無！後一章",
  "n_page": "{0} 頁",
  "delete_item_2": "刪除 {0}",
  "select_main_project_first": "請先選擇一個項目",
  "bootstart": "啟動中",
  "cancel": "放棄",
  "retry": "再試",
  "settings": "詳設細定",
  "framework": "Framework",
  "disclaimer": "免責聲明",
  "disclaimer_content": """
本軟件是個加載開發者提供的插件項目，來加載網絡資源並輕鬆瀏覽漫畫的軟件。軟件中出現的圖片資源文字，都是由插件項目以及資源網站所提供。
軟件本身不提供漫畫服務，使用漫畫資源時請遵循相關法律法規。

本軟件所提供下載的漫畫資源，版權歸原作者所有。僅供學習交流之用，請複制、下載者遵循國家相關法律、法規，在未獲得版權擁有者授權之前，勿作它用；如因非法使用引起糾紛，一切後果由使用者承擔。
  """,
  "ok": "了解",
  "language": "語言",
  "general": "通常",
  "credits": "貢獻者們",
  "credits_content": """
Liah(Icon) https://liah0227.itch.io/
""",
  "can_not_open": "不能開啟 {0}",
  "no_main_project": "無項目"
};