const Map words = {
  "app_title": "木の子",
  "confirm": "请确认",
  "install_confirm": "从 {url} 克隆项目",
  "yes": "是",
  "no": "否",
  "add": "添加",
  "clone_project": "克隆中...",
  "not_installed": "未克隆",
  "select_main_project": "设为主项目",
  "new_project": "添加Git项目",
  "new_project_hint": "Git://...",
  "add_project_failed": "没能添加，是否已经添加过了？",
  "manage_projects": "辖书斋",
  "manga_home": "漫畫之家",
  "favorites": "收藏夾",
  "chapters": "章节列表",
  "reverse_order": "逆序",
  "order": "正序",
  "no_project_found": "沒有找到這個項目",
  "can_not_determine_the_context_type": "不能識別這個數據類型",
  "download_list": "下载列表",
  "delete_item": "删除 {0}({1})",
  "undo": "取消",
  "search": "寻幽觅胜",
  "horizontal_flip": "水平翻頁",
  "vertical_flip": "垂直翻頁",
  "portrait": "竪屏",
  "landscape": "橫屏",
  "download": "下载",
  "no_prev_chapter": "沒有上一章",
  "no_next_chapter": "沒有下一章",
  "n_page": "{0} 頁",
  "delete_item_2": "删除 {0}",
  "select_main_project_first": "请先选择一个项目",
  "bootstart": "启动中",
  "cancel": "放弃",
  "retry": "再试"
};