SET(PATH "C:/Users/gen/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64")

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION Android)

SET(CMAKE_FIND_ROOT_PATH ${PATH}/sysroot/)
SET(CMAKE_C_COMPILER   ${PATH}/bin/clang.exe)
SET(CMAKE_CXX_COMPILER ${PATH}/bin/clang++.exe)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)